Include packages:


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import csv
from collections import defaultdict

Task 1:

In [31]:
"""people = ['m', 'w', 'b', 'g'] # type of peoble, men, women, boy, girl
classes = ['ae', 'ah', 'aw', 'eh', 'ei', 'er', 'ih', 'iy','oa', 'oo', 'uh', 'uw'] # all the different vowels

num_people = 4
num_classes = 12"""

#usikker på oppdeling av trening/testset. Tar bare første 70 som det står i oppgaven foreløpig, men blir da bare menn og kvinner i trening

#
features_cols = [10, 11, 12]  # 11., 12. og 13. kolonne (0-indeksert) Altså de som er 50%? usikker på om riktig

# Dictionary for å lagre data per vokalklasse
class_data = defaultdict(list)

def get_vowel_class(name):
    return name[3:5]  # Henter ut vokalen fra strengen, f.eks. 'ae' fra 'm01ae'

# Les fil + sorter dataene
with open("Data/Iris_TTT4275/vowdata_nohead.dat", "r") as file:
    data = csv.reader(file, delimiter=' ')
    for line in data:
        line = [x for x in line if x]         # Fjern eventuelle tomme elementer (pga. ekstra mellomrom)
        vowel_class = get_vowel_class(line[0])  # Hent vokalklassen
        features = [float(line[i]) for i in features_cols] # Hent de relevante feature-kolonnene og konverter til float
        class_data[vowel_class].append(features)    # Legg til i riktig vokalklasse

print(class_data)
# Konverter til dictionary med lister
class_data = dict(class_data)
print('\n')
print(class_data)
"""
# Skriv ut antall samples per klasse
for vowel, samples in class_data.items():
    print(f"Klasse '{vowel}' har {len(samples)} samples")
    print(samples)
#ser riktig ut egt
"""

defaultdict(<class 'list'>, {'ae': [[671.0, 1992.0, 2659.0], [636.0, 1881.0, 2455.0], [618.0, 1789.0, 2618.0], [720.0, 1750.0, 2435.0], [666.0, 1829.0, 2499.0], [624.0, 1925.0, 2569.0], [612.0, 1843.0, 2509.0], [562.0, 1694.0, 2614.0], [570.0, 1941.0, 2711.0], [622.0, 1885.0, 2555.0], [685.0, 1795.0, 2619.0], [608.0, 1877.0, 2520.0], [551.0, 1773.0, 2457.0], [682.0, 1695.0, 2295.0], [545.0, 2045.0, 2800.0], [633.0, 1828.0, 2603.0], [556.0, 1991.0, 3050.0], [565.0, 1817.0, 2566.0], [632.0, 1983.0, 2699.0], [628.0, 1904.0, 2515.0], [625.0, 1880.0, 2576.0], [554.0, 1819.0, 2565.0], [561.0, 1858.0, 2483.0], [638.0, 1863.0, 2513.0], [627.0, 1899.0, 2694.0], [565.0, 2040.0, 2546.0], [567.0, 1786.0, 2494.0], [624.0, 1874.0, 2604.0], [680.0, 1867.0, 2486.0], [560.0, 1945.0, 2572.0], [569.0, 1767.0, 2371.0], [651.0, 1683.0, 2413.0], [621.0, 1790.0, 2612.0], [617.0, 1721.0, 2327.0], [569.0, 1953.0, 2345.0], [642.0, 1870.0, 2488.0], [623.0, 1929.0, 2618.0], [615.0, 1624.0, 2511.0], [646.0, 1876.0

'\n# Skriv ut antall samples per klasse\nfor vowel, samples in class_data.items():\n    print(f"Klasse \'{vowel}\' har {len(samples)} samples")\n    print(samples)\n#ser riktig ut egt\n'

In [5]:
# Lagring av trenings- og testdata
train_data = {}
test_data = {}

# Del opp dataene
for vowel, data in class_data.items():
    data_array = np.array(data)  # Konverter til NumPy-array
    train_data[vowel] = data_array[:70]  # Første 70 til trening
    test_data[vowel] = data_array[70:]   # Siste 69 til test

# Beregn middelverdi og kovarians for treningssettet
mean_vectors = {}
cov_matrices = {}

for vowel, data in train_data.items():
    mean_vectors[vowel] = np.mean(data, axis=0)  # Middelverdi (gjennomsnitt per feature)
    cov_matrices[vowel] = np.cov(data, rowvar=False)  # Kovariansmatrise

# Print resultatene
for vowel in mean_vectors:
    print(f"\nVokal: {vowel}")
    print(f"Middelverdi: {mean_vectors[vowel]}")
    print(f"Kovariansmatrise:\n{cov_matrices[vowel]}")




Vokal: ae
Middelverdi: [ 661.64285714 1956.71428571 2687.22857143]
Kovariansmatrise:
[[ 6602.05900621  7416.99792961 10198.63354037]
 [ 7416.99792961 31858.75776398 32295.18219462]
 [10198.63354037 32295.18219462 54018.58467909]]

Vokal: ah
Middelverdi: [ 815.88571429 1410.12857143 2627.35714286]
Kovariansmatrise:
[[11988.4505176  11334.10186335 13338.91097308]
 [11334.10186335 27903.96873706 13177.40269151]
 [13338.91097308 13177.40269151 42944.46480331]]

Vokal: aw
Middelverdi: [ 718.6        1115.84285714 2608.8       ]
Kovariansmatrise:
[[ 7085.86666667  8096.60289855 10026.16521739]
 [ 8096.60289855 17766.4242236  12058.40289855]
 [10026.16521739 12058.40289855 46864.0173913 ]]

Vokal: eh
Middelverdi: [ 640.15714286 1869.54285714 2735.17142857]
Kovariansmatrise:
[[ 6500.22132505  9124.63809524 13937.05962733]
 [ 9124.63809524 31255.7300207  30458.54327122]
 [13937.05962733 30458.54327122 52099.65134576]]

Vokal: ei
Middelverdi: [ 454.87142857 2332.88571429 2581.11428571]
Kovarian

In [30]:
import numpy as np
import scipy.stats

# Funksjon for å klassifisere en testprøve med full kovariansmodell
def classify_sample(x, mean_vectors, cov_matrices):
    max_prob = -np.inf #vil finne største sannsynlighet så starter så lavt som mulig og oppdaterer hver gang en sansynlighet er høyere. Kan denne like gjærne være 0?
    best_class = None # vi vil finne denne, setter til none enn så lenge
    
    for vowel, mean in mean_vectors.items():
        cov = cov_matrices[vowel]
        prob = scipy.stats.multivariate_normal.logpdf(x, mean=mean, cov=cov) 
        if prob > max_prob:
                max_prob = prob
                best_class = vowel
    return best_class

# Bygg forvirringsmatrisen
confusion_matrix = {v: {v2: 0 for v2 in mean_vectors} for v in mean_vectors}

correct = 0
total = 0

for vowel, test_samples in test_data.items():
    for sample in test_samples:
        predicted = classify_sample(sample, mean_vectors, cov_matrices)
        confusion_matrix[vowel][predicted] += 1
        if predicted == vowel:
            correct += 1
        total += 1

# Print forvirringsmatrisen
print("\nConfusion Matrix:")
for v, row in confusion_matrix.items():
    print(f"{v}: {list(row.values())}")

# Beregn feilrate
error_rate = 1 - (correct / total)
print(f"\nFeilrate: {error_rate:.2%}")



Confusion Matrix:
ae: [52, 1, 0, 10, 1, 2, 3, 0, 0, 0, 0, 0]
ah: [1, 61, 2, 2, 0, 0, 0, 0, 0, 0, 3, 0]
aw: [0, 32, 29, 0, 0, 1, 0, 0, 0, 0, 6, 1]
eh: [28, 0, 0, 37, 0, 0, 4, 0, 0, 0, 0, 0]
ei: [0, 0, 0, 0, 41, 0, 5, 23, 0, 0, 0, 0]
er: [33, 0, 0, 1, 1, 34, 0, 0, 0, 0, 0, 0]
ih: [1, 0, 0, 0, 21, 0, 44, 3, 0, 0, 0, 0]
iy: [0, 0, 0, 0, 16, 0, 0, 53, 0, 0, 0, 0]
oa: [0, 0, 2, 0, 0, 0, 0, 0, 53, 3, 5, 6]
oo: [0, 0, 0, 8, 0, 6, 0, 0, 1, 49, 4, 1]
uh: [0, 3, 2, 9, 0, 0, 0, 0, 0, 7, 47, 1]
uw: [0, 0, 0, 2, 5, 13, 1, 0, 18, 5, 0, 25]

Feilrate: 36.59%


In [28]:

diagonal_matrix = {}
for vowel in mean_vectors:
    identity_matrix = np.identity(3)
    diagonal_matrix[vowel] = cov_matrices[vowel]*identity_matrix
    print(f'Diagonal matrix for {vowel}:\n {diagonal_matrix[vowel]}\n ')
    


Diagonal matrix for ae:
 [[ 6602.05900621     0.             0.        ]
 [    0.         31858.75776398     0.        ]
 [    0.             0.         54018.58467909]]
 
Diagonal matrix for ah:
 [[11988.4505176      0.             0.        ]
 [    0.         27903.96873706     0.        ]
 [    0.             0.         42944.46480331]]
 
Diagonal matrix for aw:
 [[ 7085.86666667     0.             0.        ]
 [    0.         17766.4242236      0.        ]
 [    0.             0.         46864.0173913 ]]
 
Diagonal matrix for eh:
 [[ 6500.22132505     0.             0.        ]
 [    0.         31255.7300207      0.        ]
 [    0.             0.         52099.65134576]]
 
Diagonal matrix for ei:
 [[  1775.24409938      0.              0.        ]
 [     0.          61156.18964803     -0.        ]
 [     0.             -0.         670950.30559006]]
 
Diagonal matrix for er:
 [[  1834.75465839      0.              0.        ]
 [     0.          17360.49772257      0.        ]
 [  

In [29]:
confusion_matrix = {v: {v2: 0 for v2 in mean_vectors} for v in mean_vectors}

correct = 0
total = 0

for vowel, test_samples in test_data.items():
    for sample in test_samples:
        predicted = classify_sample(sample, mean_vectors, diagonal_matrix)
        confusion_matrix[vowel][predicted] += 1
        if predicted == vowel:
            correct += 1
        total += 1
        
print("\nConfusion Matrix:")
for v, row in confusion_matrix.items():
    print(f"{v}: {list(row.values())}")

# Beregn feilrate
error_rate = 1 - (correct / total)
print(f"\nFeilrate: {error_rate:.2%}")



Confusion Matrix:
ae: [62, 1, 0, 0, 5, 0, 0, 1, 0, 0, 0, 0]
ah: [6, 63, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
aw: [0, 46, 13, 0, 0, 1, 0, 0, 0, 0, 9, 0]
eh: [65, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0]
ei: [2, 0, 0, 0, 55, 0, 4, 8, 0, 0, 0, 0]
er: [16, 0, 0, 12, 0, 38, 2, 0, 0, 0, 1, 0]
ih: [5, 0, 0, 0, 42, 0, 19, 3, 0, 0, 0, 0]
iy: [0, 0, 0, 0, 21, 0, 0, 48, 0, 0, 0, 0]
oa: [0, 0, 10, 0, 0, 0, 0, 0, 28, 13, 15, 3]
oo: [0, 0, 0, 30, 0, 0, 1, 0, 2, 17, 19, 0]
uh: [1, 17, 2, 29, 0, 0, 0, 0, 0, 0, 19, 1]
uw: [0, 0, 0, 3, 0, 5, 7, 0, 18, 27, 1, 8]

Feilrate: 54.83%
